### ISSUE TITLE
Deleting a consequence type in the active filter does not remove it from the panel filters selection

### ISSUE THREAD

**Issue by pamag** [opencb/jsorolla#382] opened 2022-01-29 12:28 UTC
## Describe the bug
Filters can be removed from the active filter, but for Consequence Type, the filters remains selected despite not being shown. Any new CT filter is added to the previous ones that where not really deleted.

Checked in both
- Sample Variant Browser
- Variant Browser

e.g:
- Removing the CT filters in the active filter does not change the selections in the left panel filters.

![delteing_CT_active-filter_issue](https://user-images.githubusercontent.com/167875/151660585-874e9cb6-029a-4565-996c-32c790852dd5.gif)

- When the CT filter is removed from the active filter, still there are filters selected but not shown. If any of the filters selected in the left panel is removed, the CT filters appear again in the active filter

![active_filter_isse_removing_CT_dont_remove_ct_list_and_reapears](https://user-images.githubusercontent.com/167875/151660800-3c8a8efd-93af-45d8-8525-5151e6bb2d4a.gif)

## Related

#376

**Comment by pamag** [comment] 2022-01-31 23:14
## Reviewed
commti: a211bb1e039c4f68309f0436a8d8ce8182da90e4


Not fully fixed. Retuirning to "in progress"

## Describe the bug
When selecting a CT alias, if, before clicking in search, the CT is removed from the active filter, the CT selected is not removed from the query, but removed visually from the active filter

## How to reproduce
1- select Loss-of-Function and MIssence alias in consequence type filter. 
2- Go to the active filter and remove the consequence type filter (the 10 CT in one go)
3- The checked boxes still are present in the left panel.
![CT_isseue](https://user-images.githubusercontent.com/167875/151888509-b5da721c-01bc-4477-957c-82de17eec911.gif)

**Comment by imedina** [comment] 2022-02-02 01:59
@pamag this not only happens with CT but with many other filters when the query is not executed yet, so this is not a bug in CT.
@jmjuanes @Rodielm @halender closing this issue, we need a new one.

**Closed by imedina** 2022-02-02 01:59 UTC
Labels: bug, variant-browser
